version: '3.9'
services:
  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    expose:
      - 6379
  app:
    build: .
    container_name: decompose_numbers
    command: yarn dev
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/usr/app
    links:
      - redis
    environment:
    - REDIS_URL=redis://cache
volumes:
  pgdata:
    driver: local
